/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as EditIdRouteImport } from './routes/edit.$id'
import { Route as DeleteIdRouteImport } from './routes/delete.$id'
import { Route as CreateReviewRouteImport } from './routes/create.review'
import { Route as CreateConfirmationRouteImport } from './routes/create.confirmation'

const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreateRoute,
} as any)
const EditIdRoute = EditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteIdRoute = DeleteIdRouteImport.update({
  id: '/delete/$id',
  path: '/delete/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateReviewRoute = CreateReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CreateRoute,
} as any)
const CreateConfirmationRoute = CreateConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => CreateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/plans': typeof PlansRoute
  '/create/confirmation': typeof CreateConfirmationRoute
  '/create/review': typeof CreateReviewRoute
  '/delete/$id': typeof DeleteIdRoute
  '/edit/$id': typeof EditIdRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/create/confirmation': typeof CreateConfirmationRoute
  '/create/review': typeof CreateReviewRoute
  '/delete/$id': typeof DeleteIdRoute
  '/edit/$id': typeof EditIdRoute
  '/create': typeof CreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRouteWithChildren
  '/plans': typeof PlansRoute
  '/create/confirmation': typeof CreateConfirmationRoute
  '/create/review': typeof CreateReviewRoute
  '/delete/$id': typeof DeleteIdRoute
  '/edit/$id': typeof EditIdRoute
  '/create/': typeof CreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/plans'
    | '/create/confirmation'
    | '/create/review'
    | '/delete/$id'
    | '/edit/$id'
    | '/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plans'
    | '/create/confirmation'
    | '/create/review'
    | '/delete/$id'
    | '/edit/$id'
    | '/create'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/plans'
    | '/create/confirmation'
    | '/create/review'
    | '/delete/$id'
    | '/edit/$id'
    | '/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRouteWithChildren
  PlansRoute: typeof PlansRoute
  DeleteIdRoute: typeof DeleteIdRoute
  EditIdRoute: typeof EditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof CreateRoute
    }
    '/edit/$id': {
      id: '/edit/$id'
      path: '/edit/$id'
      fullPath: '/edit/$id'
      preLoaderRoute: typeof EditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete/$id': {
      id: '/delete/$id'
      path: '/delete/$id'
      fullPath: '/delete/$id'
      preLoaderRoute: typeof DeleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/review': {
      id: '/create/review'
      path: '/review'
      fullPath: '/create/review'
      preLoaderRoute: typeof CreateReviewRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/confirmation': {
      id: '/create/confirmation'
      path: '/confirmation'
      fullPath: '/create/confirmation'
      preLoaderRoute: typeof CreateConfirmationRouteImport
      parentRoute: typeof CreateRoute
    }
  }
}

interface CreateRouteChildren {
  CreateConfirmationRoute: typeof CreateConfirmationRoute
  CreateReviewRoute: typeof CreateReviewRoute
  CreateIndexRoute: typeof CreateIndexRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateConfirmationRoute: CreateConfirmationRoute,
  CreateReviewRoute: CreateReviewRoute,
  CreateIndexRoute: CreateIndexRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRouteWithChildren,
  PlansRoute: PlansRoute,
  DeleteIdRoute: DeleteIdRoute,
  EditIdRoute: EditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
